{
 "title": "BiOK Overview",
 "description": "Kubernetes: Deployment Overview",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BiOK App Instance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"biok\", deployment=\"ski-biok\"}"
    }
   ]
  },
  {
   "title": "BiOK App CPU(avg/5m)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"biok\",pod_name=~\"ski-biok-[^(oz)].*\",container_name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "BiOK App Mem(avg/5m)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"biok\",pod_name=~\"ski-biok-[^(oz)].*\",container_name!=\"\"})"
    }
   ]
  },
  {
   "title": "App CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "core" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total{namespace=\"biok\",pod_name=~\"ski-biok-[^(oz)].*\",container_name!=\"\"}[2m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"biok\",pod=~\"ski-biok-[^(oz)].*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Instance Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_deployment_status_replicas_available{namespace=\"biok\",deployment=\"ski-biok\"}) by(namespace, deployment)",
     "legendFormat": "Available"
    },
    {
     "expr": "avg(kube_deployment_status_replicas_unavailable{namespace=\"biok\",deployment=\"ski-biok\"}) by(namespace, deployment)",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "avg(kube_deployment_status_replicas_updated{namespace=\"biok\",deployment=\"ski-biok\"}) by(namespace, deployment)",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "App Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (container_memory_working_set_bytes{namespace=\"biok\",pod_name=~\"ski-biok-[^(oz)].*\",container_name!=\"\"})",
     "legendFormat": "Current : {{ pod_name }} "
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"biok\",pod=~\"ski-biok-[^(oz)].*\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "OZ CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"biok\",pod_name=~\"ski-biok-oz.*\",container_name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "OZ Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"biok\",pod_name=~\"ski-biok-oz.*\",container_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Session(Redis) CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"biok\",pod_name=~\"redis-deployment.*\",container_name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Session(Redis) Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"biok\",pod_name=~\"redis-deployment.*\",container_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Traffic(TX,5m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate (container_network_transmit_bytes_total{namespace=\"biok\",pod_name=~\"ski-biok-[^(oz)].*\",interface=\"eth0\"}[5m]))"
    }
   ]
  },
  {
   "title": "Biok Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_network_transmit_bytes_total{namespace=\"biok\",pod_name=~\"ski-biok-[^(oz)].*\",interface=\"eth0\"}[5m]))",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(rate (container_network_receive_bytes_total{namespace=\"biok\",pod_name=~\"ski-biok-[^(oz)].*\",interface=\"eth0\"}[5m]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Traffic(RX,5m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 17 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate (container_network_receive_bytes_total{namespace=\"biok\",pod_name=~\"ski-biok-[^(oz)].*\",interface=\"eth0\"}[5m]))"
    }
   ]
  }
 ]
}